Cleaning up and generalizing

diff --git a/docker-upgrade b/docker-upgrade
--- a/docker-upgrade
+++ b/docker-upgrade
@@ -1,28 +1,39 @@
 #!/bin/bash
-set -e
+set -eux
 
 if [ "$#" -eq 0 ] || [ "${1:0:1}" = '-' ]; then
         set -- pg_upgrade "$@"
 fi
 
-if [ "$1" = 'pg_upgrade' ] && [ "$(id -u)" = '0' ]; then
+# If the user overrides the default usecase, let them (and bail early)
+if [ "$1" != 'pg_upgrade' ]; then
+        exec "$@"
+fi
+
+# Else, lets make sure pg_upgrade runs as expected
+
+# Make sure we use the correct user
+if [ "$(id -u)" = '0' ]; then
         mkdir -p "$PGDATAOLD" "$PGDATANEW"
         chmod 700 "$PGDATAOLD" "$PGDATANEW"
         chown postgres .
         chown -R postgres "$PGDATAOLD" "$PGDATANEW"
-        exec gosu postgres "$BASH_SOURCE" "$@"
+        # Exec this script again (with a different user)
+        exec gosu postgres "${BASH_SOURCE[0]}" "$@"
 fi
 
-if [ "$1" = 'pg_upgrade' ]; then
-        if [ ! -s "$PGDATANEW/PG_VERSION" ]; then
-                PGDATA="$PGDATANEW" eval "initdb $POSTGRES_INITDB_ARGS"
+if [ ! -s "$PGDATANEW/PG_VERSION" ]; then
+        PGDATA="$PGDATANEW" eval "initdb $POSTGRES_INITDB_ARGS"
+fi
+
+if [ -n "${TIMESCALEDB_VERSION}" ]; then
+        echo "shared_preload_libraries = 'timescaledb'" >> "${PGDATANEW}/postgresql.conf"
+fi
+
+# Run and handle potential failure
+if ! eval "$*"; then
+        if [ -f "loadable_libraries.txt" ]; then
+                cat loadable_libraries.txt
         fi
 fi
 
-echo "shared_preload_libraries = 'timescaledb'" >> /var/lib/postgresql/13/data/postgresql.conf
-
-eval "pg_upgrade $@" || :
-
-if [ -f "loadable_libraries.txt" ]; then
-        cat loadable_libraries.txt
-fi
